image: node:15.5.1

before_script:
  - yarn
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

publish:
  stage: deploy
  script:
    - yarn run publish:package
    - yarn run publish:docs
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+.*/
  except:
    - branches